nome = input ("Digite seu nome: ")
sobrenome = input ("Digite seu sobrenome: ")
print (f"Seu nome é {nome} {sobrenome}")
print (nome, sobrenome, sep = "#")
print (f"Seu nome é {nome} {sobrenome}", end="...\n")